In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('data/charities_with_deprivation.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data/charities_with_deprivation.csv'

In [ ]:
df.head()

,Unnamed: 0_x,Charity Number,Charity Name,Charity Address,Charity Postcode,Charity Constituency,Phone,Email,Website,Last Recorded Financial Year,Last Recorded Income,Last Recorded Expenditure,Charity Type,How the charity helps,What the charity does,Who the charity helps,Activities,Charity Objects,TH Postcode,Charity Size Band,Size Band,Primary Focus,lsoa21,lat,long,Unnamed: 0_y,LSOA code (2021),LSOA name (2021),Local Authority District code (2024),Local Authority District name (2024),Index of Multiple Deprivation (IMD) Score,Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived),Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs),Income Score (rate),Income Rank (where 1 is most deprived),Income Decile (where 1 is most deprived 10% of LSOAs),Employment Score (rate),Employment Rank (where 1 is most deprived),Employment Decile (where 1 is most deprived 10% of LSOAs),"Education, Skills and Training Score","Education, Skills and Training Rank (where 1 is most deprived)","Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)",Health Deprivation and Disability Score,Health Deprivation and Disability Rank (where 1 is most deprived),Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs),Crime Score,Crime Rank (where 1 is most deprived),Crime Decile (where 1 is most deprived 10% of LSOAs),Barriers to Housing and Services Score,Barriers to Housing and Services Rank (where 1 is most deprived),Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs),Living Environment Score,Living Environment Rank (where 1 is most deprived),Living Environment Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Children Index (IDACI) Score (rate),Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived),Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs),Income Deprivation Affecting Older People (IDAOPI) Score (rate),Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived),Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs),Children and Young People Sub-domain Score,Children and Young People Sub-domain Rank (where 1 is most deprived),Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSO,Adult Skills Sub-domain Score,Adult Skills Sub-domain Rank (where 1 is most deprived),Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Geographical Barriers Sub-domain Score,Geographical Barriers Sub-domain Rank (where 1 is most deprived),Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Wider Barriers Sub-domain Score,Wider Barriers Sub-domain Rank (where 1 is most deprived),Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Indoors Sub-domain Score,Indoors Sub-domain Rank (where 1 is most deprived),Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Outdoors Sub-domain Score,Outdoors Sub-domain Rank (where 1 is most deprived),Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs),Total population: mid 2022,Dependent Children aged 0-15: mid 2022,Older population aged 60 and over: mid 2022,Working age population 18-66 (for use with Employment Deprivation Domain): mid 2022
0,1,206431,CHARITY OF MARY BAKER,"32 MONTHOPE ROAD, LONDON",E1 5LS,Bethnal Green and Stepney,02073771086,Not available,www.marybaker.org.uk,31/12/2024,8523.0,7908.0,Other,"Makes Grants To Individuals, Makes Grants To O...",The Prevention Or Relief Of Poverty,The General Public/mankind,The charity operates in the London Borough of ...,TO RELIEVE EITHER GENERALLY OR INDIVIDUALLY PE...,True,Micro,Dormant,The Prevention Or Relief Of Poverty,E01004306,51.517898,-0.069152,4077.0,E01004306,Tower Hamlets 015A,E09000030,Tower Hamlets,36.117,5760.0,2.0,0.387,5779.0,2.0,0.190,7476.0,3.0,15.221,17960.0,6.0,0.546,9106.0,3.0,0.730,6662.0,2.0,38.717,2518.0,1.0,48.653,2506.0,1.0,0.570,5626.0,2.0,0.583,1307.0,1.0,-0.348,21744.0,7.0,0.251,13590.0,5.0,2.072,33743.0,10.0,6.372,739.0,1.0,0.378,9252.0,3.0,2.266,120.0,1.0,1926.0,302.0,204.0,1448.0
1,5,207772,HENRY FAWCETT FUND,"ST PETER'S CHURCH OFFICE, The Vicarage, St. Pe...",E2 7AE,Bethnal Green and Stepney,02070330244,info@stpetersbethnalgreen.org,Not available,31/12/2024,103540.0,22604.0,Other,"Makes Grants To Individuals, Makes Grants To O...","General Charitable Purposes, Education/trainin...","Children/young People, Elderly/old People, Peo...",The charity is restricted to the benefit of pe...,"GENERAL BENEFIT OF POOR PERSONS, IF POSSIBLE T...",True,Medium,Dormant,Accommodation/housing,E01004204,51.529956,-0.064186,4001.0,E01004204,Tower Hamlets 005D,E09000030,Tower Hamlets,37.469,5300.0,2.0,0.472,3206.0,1.0,0.191,7379.0,3.0,18.864,15177.0,5.0,0.728,7154.0,3.0,0.473,9908.0,3.0,32.576,5066.0,2.0,44.911,3388.0,2.0,0.761,1323.0,1.0,0.636,830.0,1.0,-0.389,22367.0,7.0,0.292,9501.0,3.0,3.661,33625.0,10.0,5.470,1579.0,1.0,0.233,11484.0,4.0,2.219,154.0,1.0,1876.0,319.0,275.0,1336.0
2,6,208870,SALMON LANE MISSION,"168-170 SALMON LANE, LIMEHOUSE, LONDON",E14 7PQ,Poplar and Limehouse,02079879960,Not available,Not available,30/09/2024,15920.0,10862.0,Charitable company,"Provides Buildings/facilities/open Space, Prov...","Education/training, The Prevention Or Relief O...",The General Public/mankind,"The work consists of promoting, organising, co...","TO PROMOTE, ORGANISE, CONDUCT AND CARRY ON CHA...",True,Small,Dormant,Overseas Aid/famine Relief,E01035690,51.513730,-0.033758,33683.0,E01035690,Tower Hamlets 023E,E09000030,Tower Hamlets,16.612,17643.0,6.0,0.237,13109.0,4.0,0.073,24709.0,8.0,13.312,19568.0,6.0,-0.030,16879.0,6.0,0.153,14517.0,5.0,26.087,9801.0,3.0,24.595,12327.0,4.0,0.557,6013.0,2.0,0.878,95.0,1.0,-0.043,17058.0,6.0,0.197,20559.0,7.0,6.891,33253.0,10.0,4.365,3150.0,1.0,-0.499,26262.0,8.0,1.518,1283.0,1.0,2106.0,284.0,48.0,1754.0
3,7,209117,THE STRANGERS REST MISSION,"Strangers Rest Church, 131 The Highway, LONDON",E1W 2BP,Bethnal Green and Stepney,0795 6188 505,mlrmullins@gmail.com,http://www.strangersrest.org/,30/09/2024,40208.0,48706.0,Other,"Provides Human Resources, Provides Buildings/f...","Disability, The Prevention Or Relief Of Povert...","Children/young People, Elderly/old People, Peo...",THE STRANGERS' REST MISSION IS A CHRISTIAN ORG...,EVANGELISTIC CHRISTIAN MISSION PURPOSES IN THE...,True,Small,Dormant,Disability,E01004295,51.509574,-0.061751,4067.0,E01004295,Tower Hamlets 026C,E09000030,Tower Hamlets,39.106,4826.0,2.0,0.602,868.0,1.0,0.153,10980.0,4.0,21.833,13150.0,4.0,-0.004,16476.0,5.0,0.188,13981.0,5.0,42.923,1408.0,1.0,35.935,6506.0,2.0,0.861,443.0,1.0,0.623,932.0,1.0,-0.808,27733.0,9.0,0.340,5776.0,2.0,3.516,33637.0,10.0,7.036,380.0,1.0,-0.199,19993.0,6.0,2.193,181.0,1.0,2052.0,543.0,194.0,1326.0
4,9,210928,EAST LONDON NURSING SOCIETY TRUST,"45-55 Whitehorse Road, LONDON",E1 0ND,Bethnal Green and Stepney,02077909085,info@towerproject.org.uk,Not available,31/03/2024,17556.0,4896.0,Other,Makes Grants To Organisations,"The Advancement Of Health Or Saving Of Lives, ...","Children/young People, Elderly/old People, Peo...",Making grants to groups providing support for ...,TO RELIEVE IN CASES OF NEED PERSONS RESIDENT I...,True,Small,Dormant,Disability,E01004286,51.513692,-0.040620,4059.0,E01004286,Tower Hamlets 019C,E09000030,Tower Hamlets,38.909,4894.0,2.0,0.432,4299.0,2.0,0.223,5156.0,2.0,19.673,14592.0,5.0,0.458,10198.0,4.0,0.953,4494.0,2.0,37.938,2784.0,1.0,39.925,4958.0,2.0,0.508,7751.0,3.0,0.674,587.0,1.0,-0.624,25611.0,8.0,0.313,7672.0,3.0,6.577,33309.0,10.0,6.255,838.0,1.0,0.185,12251.0,4.0,1.827,619.0,1.0,2565.0,491.0,320.0,1786.0

In [ ]:
drop_cols = [
    'Unnamed: 0_x',
    'Unnamed: 0_y',
    'Phone', 'Email', 'Website',
    'Charity Type',
    'TH Postcode',
    'Size Band',
    'LSOA code (2021)',
    'LSOA name (2021)',
    'Local Authority District code (2024)',
    'Local Authority District name (2024)',
    'Index of Multiple Deprivation (IMD) Rank (where 1 is most deprived)',
    'Income Rank (where 1 is most deprived)',
    'Income Decile (where 1 is most deprived 10% of LSOAs)',
    'Employment Rank (where 1 is most deprived)',
    'Employment Decile (where 1 is most deprived 10% of LSOAs)',
    'Education, Skills and Training Rank (where 1 is most deprived)',
    'Education, Skills and Training Decile (where 1 is most deprived 10% of LSOAs)',
    'Health Deprivation and Disability Rank (where 1 is most deprived)',
    'Health Deprivation and Disability Decile (where 1 is most deprived 10% of LSOAs)',
    'Crime Rank (where 1 is most deprived)',
    'Crime Decile (where 1 is most deprived 10% of LSOAs)',
    'Barriers to Housing and Services Rank (where 1 is most deprived)',
    'Barriers to Housing and Services Decile (where 1 is most deprived 10% of LSOAs)',
    'Living Environment Rank (where 1 is most deprived)',
    'Living Environment Decile (where 1 is most deprived 10% of LSOAs)',
    'Income Deprivation Affecting Children Index (IDACI) Score (rate)',
    'Income Deprivation Affecting Children Index (IDACI) Rank (where 1 is most deprived)',
    'Income Deprivation Affecting Children Index (IDACI) Decile (where 1 is most deprived 10% of LSOAs)',
    'Income Deprivation Affecting Older People (IDAOPI) Score (rate)',
    'Income Deprivation Affecting Older People (IDAOPI) Rank (where 1 is most deprived)',
    'Income Deprivation Affecting Older People (IDAOPI) Decile (where 1 is most deprived 10% of LSOAs)',
    'Children and Young People Sub-domain Score',
    'Children and Young People Sub-domain Rank (where 1 is most deprived)',
    'Children and Young People Sub-domain Decile (where 1 is most deprived 10% of LSO',
    'Adult Skills Sub-domain Score',
    'Adult Skills Sub-domain Rank (where 1 is most deprived)',
    'Adult Skills Sub-domain Decile (where 1 is most deprived 10% of LSOAs)',
    'Geographical Barriers Sub-domain Score',
    'Geographical Barriers Sub-domain Rank (where 1 is most deprived)',
    'Geographical Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)',
    'Wider Barriers Sub-domain Score',
    'Wider Barriers Sub-domain Rank (where 1 is most deprived)',
    'Wider Barriers Sub-domain Decile (where 1 is most deprived 10% of LSOAs)',
    'Indoors Sub-domain Score',
    'Indoors Sub-domain Rank (where 1 is most deprived)',
    'Indoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)',
    'Outdoors Sub-domain Score',
    'Outdoors Sub-domain Rank (where 1 is most deprived)',
    'Outdoors Sub-domain Decile (where 1 is most deprived 10% of LSOAs)',
    'Working age population 18-66 (for use with Employment Deprivation Domain): mid 2022'
]

df = df.drop(columns=drop_cols)

In [ ]:
df.columns

Index(['Charity Number', 'Charity Name', 'Charity Address', 'Charity Postcode',
       'Last Recorded Financial Year', 'Last Recorded Income',
       'Last Recorded Expenditure', 'How the charity helps',
       'What the charity does', 'Who the charity helps', 'Activities',
       'Charity Objects', 'Charity Size Band', 'Primary Focus', 'lsoa21',
       'lat', 'long', 'Index of Multiple Deprivation (IMD) Score',
       'Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)',
       'Income Score (rate)', 'Employment Score (rate)',
       'Education, Skills and Training Score',
       'Health Deprivation and Disability Score', 'Crime Score',
       'Barriers to Housing and Services Score', 'Living Environment Score',
       'Total population: mid 2022', 'Dependent Children aged 0-15: mid 2022',
       'Older population aged 60 and over: mid 2022'],
      dtype='str')

In [ ]:
df = df.rename(columns={
    'Charity Number': 'id',
    'Charity Name': 'name',
    'Charity Address': 'address',
    'Charity Postcode': 'postcode',
    'Last Recorded Income': 'income',
    'Last Recorded Expenditure': 'expenditure',
    'How the charity helps': 'howHelps',
    'What the charity does': 'whatDoes',
    'Who the charity helps': 'whoHelps',
    'Activities': 'activities',
    'Charity Size Band': 'sizeBand',
    'Primary Focus': 'primaryFocus',
    'lsoa21': 'lsoaCode',
    'lat': 'lat',
    'long': 'lng',
    'Index of Multiple Deprivation (IMD) Score': 'imdScore',
    'Index of Multiple Deprivation (IMD) Decile (where 1 is most deprived 10% of LSOAs)': 'imdDecile',
    'Income Score (rate)': 'incomeScore',
    'Employment Score (rate)': 'employmentRate',
    'Health Deprivation and Disability Score': 'healthDeprivation',
    'Crime Score': 'crimeDeprivation',
    'Barriers to Housing and Services Score': 'housingBarriersDeprivation',
    'Living Environment Score': 'livingEnvScore',
    'Total population: mid 2022': 'totalPopulation',
    'Dependent Children aged 0-15: mid 2022': 'childPopulation',
    'Older population aged 60 and over: mid 2022': 'olderPopulation',
    'Charity Objects':'aim',
    'Education, Skills and Training Score': 'educationSkillsTrainingScore',
    'Last Recorded Financial Year':'lastRecordedFinancialYear',
    'Charity Constituency':'constituency'
})

In [ ]:
df.columns

Index(['id', 'name', 'address', 'postcode', 'lastRecordedFinancialYear',
       'income', 'expenditure', 'howHelps', 'whatDoes', 'whoHelps',
       'activities', 'aim', 'sizeBand', 'primaryFocus', 'lsoaCode', 'lat',
       'lng', 'imdScore', 'imdDecile', 'incomeScore', 'employmentRate',
       'educationSkillsTrainingScore', 'healthDeprivation', 'crimeDeprivation',
       'housingBarriersDeprivation', 'livingEnvScore', 'totalPopulation',
       'childPopulation', 'olderPopulation'],
      dtype='str')

In [ ]:
df.head()

,id,name,address,postcode,lastRecordedFinancialYear,income,expenditure,howHelps,whatDoes,whoHelps,activities,aim,sizeBand,primaryFocus,lsoaCode,lat,lng,imdScore,imdDecile,incomeScore,employmentRate,educationSkillsTrainingScore,healthDeprivation,crimeDeprivation,housingBarriersDeprivation,livingEnvScore,totalPopulation,childPopulation,olderPopulation
0,206431,CHARITY OF MARY BAKER,"32 MONTHOPE ROAD, LONDON",E1 5LS,31/12/2024,8523.0,7908.0,"Makes Grants To Individuals, Makes Grants To O...",The Prevention Or Relief Of Poverty,The General Public/mankind,The charity operates in the London Borough of ...,TO RELIEVE EITHER GENERALLY OR INDIVIDUALLY PE...,Micro,The Prevention Or Relief Of Poverty,E01004306,51.517898,-0.069152,36.117,2.0,0.387,0.190,15.221,0.546,0.730,38.717,48.653,1926.0,302.0,204.0
1,207772,HENRY FAWCETT FUND,"ST PETER'S CHURCH OFFICE, The Vicarage, St. Pe...",E2 7AE,31/12/2024,103540.0,22604.0,"Makes Grants To Individuals, Makes Grants To O...","General Charitable Purposes, Education/trainin...","Children/young People, Elderly/old People, Peo...",The charity is restricted to the benefit of pe...,"GENERAL BENEFIT OF POOR PERSONS, IF POSSIBLE T...",Medium,Accommodation/housing,E01004204,51.529956,-0.064186,37.469,2.0,0.472,0.191,18.864,0.728,0.473,32.576,44.911,1876.0,319.0,275.0
2,208870,SALMON LANE MISSION,"168-170 SALMON LANE, LIMEHOUSE, LONDON",E14 7PQ,30/09/2024,15920.0,10862.0,"Provides Buildings/facilities/open Space, Prov...","Education/training, The Prevention Or Relief O...",The General Public/mankind,"The work consists of promoting, organising, co...","TO PROMOTE, ORGANISE, CONDUCT AND CARRY ON CHA...",Small,Overseas Aid/famine Relief,E01035690,51.513730,-0.033758,16.612,6.0,0.237,0.073,13.312,-0.030,0.153,26.087,24.595,2106.0,284.0,48.0
3,209117,THE STRANGERS REST MISSION,"Strangers Rest Church, 131 The Highway, LONDON",E1W 2BP,30/09/2024,40208.0,48706.0,"Provides Human Resources, Provides Buildings/f...","Disability, The Prevention Or Relief Of Povert...","Children/young People, Elderly/old People, Peo...",THE STRANGERS' REST MISSION IS A CHRISTIAN ORG...,EVANGELISTIC CHRISTIAN MISSION PURPOSES IN THE...,Small,Disability,E01004295,51.509574,-0.061751,39.106,2.0,0.602,0.153,21.833,-0.004,0.188,42.923,35.935,2052.0,543.0,194.0
4,210928,EAST LONDON NURSING SOCIETY TRUST,"45-55 Whitehorse Road, LONDON",E1 0ND,31/03/2024,17556.0,4896.0,Makes Grants To Organisations,"The Advancement Of Health Or Saving Of Lives, ...","Children/young People, Elderly/old People, Peo...",Making grants to groups providing support for ...,TO RELIEVE IN CASES OF NEED PERSONS RESIDENT I...,Small,Disability,E01004286,51.513692,-0.040620,38.909,2.0,0.432,0.223,19.673,0.458,0.953,37.938,39.925,2565.0,491.0,320.0