# Lower Layer Super Output Areas

The Lower Layer Super Output Areas data contains a micro breakdown of London, specifically a neighbourhood breakdown. In this notebook I inspect the data and more importantly filter for Tower Hamlets areas.

Retrieved From: https://geoportal.statistics.gov.uk/datasets/ons::lower-layer-super-output-areas-december-2021-boundaries-ew-bsc-v4-2/about

In [1]:
import pandas as pd
import json

## CSV LSOA

In [7]:
df = pd.read_csv('../data/raw_data/lsoa/Lower_layer_Super_Output_Areas_December_2021_Boundaries_EW_BSC_V4_3901388190129020682.csv')

In [8]:
df.head()

,FID,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,Shape__Area,Shape__Length,GlobalID
0,1,E01000001,City of London 001A,,532123,181632,51.51817,-0.097150,157794.837975,1685.391557,3478c558-3297-4e2b-979e-e29dd9ff3bf5
1,2,E01000002,City of London 001B,,532480,181715,51.51883,-0.091970,164882.111366,1804.827316,f2072109-b1ae-426c-b166-083cc32f1789
2,3,E01000003,City of London 001C,,532239,182033,51.52174,-0.095330,42216.046440,909.253080,a9009c33-9b6b-4230-ba62-fc3264806de4
3,4,E01000005,City of London 001E,,533581,181283,51.51469,-0.076280,212700.741287,2028.716721,86aee0aa-079f-4f92-8f9d-5773824f4945
4,5,E01000006,Barking and Dagenham 016A,,544994,184274,51.53875,0.089317,130551.232040,1716.731235,c33f1f5b-6b15-47a1-b046-b6a148a9f6d3

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35672 entries, 0 to 35671
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FID            35672 non-null  int64
 1   LSOA21CD       35672 non-null  str
 2   LSOA21NM       35672 non-null  str
 3   LSOA21NMW      35672 non-null  str
 4   BNG_E          35672 non-null  int64
 5   BNG_N          35672 non-null  int64
 6   LAT            35672 non-null  float64
 7   LONG           35672 non-null  float64
 8   Shape__Area    35672 non-null  float64
 9   Shape__Length  35672 non-null  float64
 10  GlobalID       35672 non-null  str
dtypes: float64(4), int64(3), str(4)
memory usage: 3.0 MB

In [10]:
df[df['LSOA21NM'].str.contains("Tower Hamlets")]

,FID,LSOA21CD,LSOA21NM,LSOA21NMW,BNG_E,BNG_N,LAT,LONG,Shape__Area,Shape__Length,GlobalID
3995,3996,E01004198,Tower Hamlets 002B,,535012,183130,51.53094,-0.05496,52288.923340,1196.197890,d2c00273-5576-4419-b512-f44a7bead29a
3996,3997,E01004199,Tower Hamlets 002C,,534754,183031,51.53012,-0.05872,60796.077866,1119.569773,f2febfb4-cc4b-442a-bde5-026947a7b905
3997,3998,E01004200,Tower Hamlets 005A,,534519,183093,51.53073,-0.06208,62091.637253,1006.626653,3880fc11-1461-441d-a8a1-c2ee45824e18
3998,3999,E01004201,Tower Hamlets 002D,,535390,183327,51.53262,-0.04944,157286.302925,1704.863816,1c69e8b2-1fcf-40d4-b69b-8f9f1b577e29
3999,4000,E01004202,Tower Hamlets 005B,,534615,183389,51.53337,-0.06058,130947.069221,1464.520206,fc7f8670-271a-42cd-8eee-86bd2262ced2
...,...,...,...,...,...,...,...,...,...,...,...
33695,33696,E01035702,Tower Hamlets 034C,,538852,181018,51.51104,-0.00047,396269.688271,3030.729621,22e6ce9a-e8fe-4dbc-a454-5ffeea3ffdf6
33696,33697,E01035703,Tower Hamlets 036B,,537873,179599,51.49852,-0.01512,52487.329781,962.366225,b84f7d89-0265-4464-91ce-c4e3f35bfc51
33697,33698,E01035704,Tower Hamlets 036C,,537889,179405,51.49678,-0.01497,13759.493034,621.146662,91b3d4e5-0ccc-4c18-b903-4327d01bcd16
33698,33699,E01035705,Tower Hamlets 036D,,538199,179384,51.49651,-0.01051,154129.566368,1591.939998,2678f26d-b370-4ad5-b54c-5171896c3f07
33699,33700,E01035706,Tower Hamlets 036E,,537901,179182,51.49477,-0.01488,84331.630096,1238.897109,73bd7dba-4c61-41b1-91a5-87fe6af10444

As we can see there are 169 LSOA codes in Tower Hamlets, now I will import the GeoJSON version of this dataset to confirm that there are indeed 169 in that file which will be used to create the map in the app.

## GeoJSON LSOA

In [3]:
with open('../data/raw_data/lsoa/Lower_layer_Super_Output_Areas_December_2021_Boundaries_EW_BSC_V4_-4299016806856585929.geojson', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [ ]:
tower_hamlets_only = [
    feature for feature in data['features']
    if 'Tower Hamlets' in feature['properties'].get('LSOA21NM', '')
]

In [ ]:
filtered_data = {
    "type": "FeatureCollection",
    "name": "Tower_Hamlets_LSOA",
    "crs": data.get("crs"),
    "features": tower_hamlets_only
}

Exporting the Tower Hamlets-specific GeoJSON.

In [6]:
with open('../data/clean_data/lsoa_clean.geojson', 'w', encoding='utf-8') as f:
    json.dump(filtered_data, f)

#### Inspecting the filtered GeoJSON file

In [11]:
with open('../data/clean_data/lsoa_clean.geojson', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [14]:
print(f"Number of rows: {len(data['features'])}")

Number of rows: 169

As we can see again we have 169 rows of LSOA codes within Tower Hamlets which coincides with both the deprivation_data and the LSOA CSV in this notebook. We can now proceed to inspect the charity data.