In [56]:
import pandas as pd
import plotly.graph_objects as go

In [57]:
df = pd.read_csv("../charity_watch_streamlit/data/charities_with_deprivation.csv")

In [58]:
imd_categories_breakdown = {
    "incomeScore":"Income",
    "employmentRate":'Employement',
    "educationSkillsTrainingScore": "Education",
    "healthDeprivation":"Health",
    "crimeDeprivation" :"Crime",
    "housingBarriersDeprivation":"Housing",
    "livingEnvScore":"Living Environment",
}

In [59]:
imd_column_names = list(imd_categories_breakdown.keys())
imd_column_names

['incomeScore',
 'employmentRate',
 'educationSkillsTrainingScore',
 'healthDeprivation',
 'crimeDeprivation',
 'housingBarriersDeprivation',
 'livingEnvScore']

In [60]:
lsoa_imd_scores = df.drop_duplicates(subset="lsoaCode")[["lsoaCode"] + imd_column_names].copy()

In [61]:
lsoa_imd_scores

,lsoaCode,incomeScore,employmentRate,educationSkillsTrainingScore,healthDeprivation,crimeDeprivation,housingBarriersDeprivation,livingEnvScore
0,E01004306,0.387,0.190,15.221,0.546,0.730,38.717,48.653
1,E01004204,0.472,0.191,18.864,0.728,0.473,32.576,44.911
2,E01035690,0.237,0.073,13.312,-0.030,0.153,26.087,24.595
3,E01004295,0.602,0.153,21.833,-0.004,0.188,42.923,35.935
4,E01004286,0.432,0.223,19.673,0.458,0.953,37.938,39.925
...,...,...,...,...,...,...,...,...
277,E01004214,0.730,0.257,31.042,0.853,0.230,46.035,21.057
287,E01004209,0.599,0.225,25.547,0.853,0.714,38.226,49.823
290,E01004218,0.232,0.099,6.022,-0.716,-0.430,37.046,16.663
291,E01035694,0.573,0.246,22.486,0.950,0.794,35.705,33.370
293,E01004324,0.537,0.207,27.841,0.680,0.440,46.943,27.103

In [62]:
for i, j in imd_categories_breakdown.items():
        lsoa_imd_scores[f"{i}_percentage"] = lsoa_imd_scores[i].rank(pct=True) * 100

In [63]:
lsoa_imd_scores

,lsoaCode,incomeScore,employmentRate,educationSkillsTrainingScore,healthDeprivation,crimeDeprivation,housingBarriersDeprivation,livingEnvScore,incomeScore_percentage,employmentRate_percentage,educationSkillsTrainingScore_percentage,healthDeprivation_percentage,crimeDeprivation_percentage,housingBarriersDeprivation_percentage,livingEnvScore_percentage
0,E01004306,0.387,0.190,15.221,0.546,0.730,38.717,48.653,39.024390,67.886179,47.967480,56.097561,65.040650,75.609756,94.308943
1,E01004204,0.472,0.191,18.864,0.728,0.473,32.576,44.911,60.162602,70.325203,62.601626,73.983740,43.089431,47.154472,86.178862
2,E01035690,0.237,0.073,13.312,-0.030,0.153,26.087,24.595,11.382114,10.569106,36.585366,13.008130,17.073171,20.325203,13.821138
3,E01004295,0.602,0.153,21.833,-0.004,0.188,42.923,35.935,91.056911,46.341463,70.731707,14.634146,20.325203,89.430894,60.975610
4,E01004286,0.432,0.223,19.673,0.458,0.953,37.938,39.925,51.219512,86.991870,65.853659,50.406504,89.430894,72.357724,74.796748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,E01004214,0.730,0.257,31.042,0.853,0.230,46.035,21.057,100.000000,99.186992,95.121951,84.959350,21.138211,93.495935,6.504065
287,E01004209,0.599,0.225,25.547,0.853,0.714,38.226,49.823,90.243902,87.804878,84.552846,84.959350,63.414634,73.983740,95.934959
290,E01004218,0.232,0.099,6.022,-0.716,-0.430,37.046,16.663,10.569106,15.853659,8.943089,1.626016,4.065041,68.292683,4.878049
291,E01035694,0.573,0.246,22.486,0.950,0.794,35.705,33.370,84.552846,94.308943,72.764228,89.837398,76.422764,60.162602,44.715447
293,E01004324,0.537,0.207,27.841,0.680,0.440,46.943,27.103,76.422764,79.674797,92.682927,68.292683,39.430894,96.747967,24.390244

In [64]:
lsoa_imd_dict = {}

In [65]:
#now we turn this dataframe into a dictionary of dictionaries, one lsoa key and its imd scores as values
for _, j in lsoa_imd_scores.iterrows():
    lsoa_code = j["lsoaCode"]
    lsoa_imd_dict[lsoa_code] = {
        label: round(j[f"{i}_percentage"], 1) for i, label in imd_categories_breakdown.items()}

In [66]:
lsoa_imd_dict

{'E01004306': {'Income': 39.0,
  'Employement': 67.9,
  'Education': 48.0,
  'Health': 56.1,
  'Crime': 65.0,
  'Housing': 75.6,
  'Living Environment': 94.3},
 'E01004204': {'Income': 60.2,
  'Employement': 70.3,
  'Education': 62.6,
  'Health': 74.0,
  'Crime': 43.1,
  'Housing': 47.2,
  'Living Environment': 86.2},
 'E01035690': {'Income': 11.4,
  'Employement': 10.6,
  'Education': 36.6,
  'Health': 13.0,
  'Crime': 17.1,
  'Housing': 20.3,
  'Living Environment': 13.8},
 'E01004295': {'Income': 91.1,
  'Employement': 46.3,
  'Education': 70.7,
  'Health': 14.6,
  'Crime': 20.3,
  'Housing': 89.4,
  'Living Environment': 61.0},
 'E01004286': {'Income': 51.2,
  'Employement': 87.0,
  'Education': 65.9,
  'Health': 50.4,
  'Crime': 89.4,
  'Housing': 72.4,
  'Living Environment': 74.8},
 'E01004268': {'Income': 72.0,
  'Employement': 74.8,
  'Education': 72.8,
  'Health': 81.3,
  'Crime': 11.4,
  'Housing': 48.0,
  'Living Environment': 48.0},
 'E01004249': {'Income': 87.8,
  'Employement': 92.7,
  'Education': 95.9,
  'Health': 34.1,
  'Crime': 56.9,
  'Housing': 83.7,
  'Living Environment': 41.5},
 'E01035670': {'Income': 13.8,
  'Employement': 13.0,
  'Education': 87.8,
  'Health': 12.2,
  'Crime': 67.5,
  'Housing': 65.9,
  'Living Environment': 69.9},
 'E01004203': {'Income': 37.4,
  'Employement': 35.0,
  'Education': 41.5,
  'Health': 43.9,
  'Crime': 94.3,
  'Housing': 34.1,
  'Living Environment': 78.0},
 'E01035675': {'Income': 44.7,
  'Employement': 30.5,
  'Education': 56.1,
  'Health': 56.9,
  'Crime': 52.0,
  'Housing': 84.6,
  'Living Environment': 59.3},
 'E01004234': {'Income': 5.7,
  'Employement': 11.4,
  'Education': 4.1,
  'Health': 2.4,
  'Crime': 61.8,
  'Housing': 13.8,
  'Living Environment': 97.6},
 'E01004241': {'Income': 95.1,
  'Employement': 95.1,
  'Education': 87.0,
  'Health': 91.9,
  'Crime': 26.0,
  'Housing': 86.2,
  'Living Environment': 11.4},
 'E01004290': {'Income': 42.7,
  'Employement': 47.6,
  'Education': 57.7,
  'Health': 66.7,
  'Crime': 57.7,
  'Housing': 36.6,
  'Living Environment': 43.1},
 'E01035664': {'Income': 36.6,
  'Employement': 58.5,
  'Education': 16.3,
  'Health': 54.5,
  'Crime': 85.4,
  'Housing': 22.0,
  'Living Environment': 93.5},
 'E01004236': {'Income': 99.2,
  'Employement': 95.9,
  'Education': 97.6,
  'Health': 89.8,
  'Crime': 49.2,
  'Housing': 30.9,
  'Living Environment': 58.5},
 'E01004211': {'Income': 25.2,
  'Employement': 36.6,
  'Education': 19.5,
  'Health': 35.8,
  'Crime': 98.4,
  'Housing': 67.5,
  'Living Environment': 99.2},
 'E01032772': {'Income': 25.2,
  'Employement': 15.9,
  'Education': 31.7,
  'Health': 52.0,
  'Crime': 13.8,
  'Housing': 7.3,
  'Living Environment': 3.3},
 'E01032786': {'Income': 65.0,
  'Employement': 62.2,
  'Education': 60.2,
  'Health': 35.0,
  'Crime': 53.7,
  'Housing': 64.2,
  'Living Environment': 39.0},
 'E01004280': {'Income': 45.5,
  'Employement': 47.6,
  'Education': 58.5,
  'Health': 24.0,
  'Crime': 8.9,
  'Housing': 35.8,
  'Living Environment': 28.5},
 'E01004283': {'Income': 75.6,
  'Employement': 70.3,
  'Education': 74.0,
  'Health': 87.8,
  'Crime': 44.7,
  'Housing': 78.9,
  'Living Environment': 36.6},
 'E01004244': {'Income': 69.9,
  'Employement': 90.2,
  'Education': 82.1,
  'Health': 94.3,
  'Crime': 87.8,
  'Housing': 65.0,
  'Living Environment': 38.2},
 'E01004322': {'Income': 98.4,
  'Employement': 42.7,
  'Education': 56.9,
  'Health': 96.7,
  'Crime': 32.9,
  'Housing': 51.2,
  'Living Environment': 87.0},
 'E01004198': {'Income': 63.4,
  'Employement': 97.6,
  'Education': 85.4,
  'Health': 95.1,
  'Crime': 91.1,
  'Housing': 78.0,
  'Living Environment': 53.7},
 'E01035691': {'Income': 6.9,
  'Employement': 2.4,
  'Education': 22.0,
  'Health': 5.7,
  'Crime': 47.2,
  'Housing': 24.4,
  'Living Environment': 26.0},
 'E01004291': {'Income': 4.9,
  'Employement': 8.1,
  'Education': 4.9,
  'Health': 6.5,
  'Crime': 13.0,
  'Housing': 2.4,
  'Living Environment': 56.1},
 'E01004303': {'Income': 50.4,
  'Employement': 61.0,
  'Education': 59.3,
  'Health': 27.6,
  'Crime': 45.5,
  'Housing': 61.8,
  'Living Environment': 35.0},
 'E01004272': {'Income': 85.4,
  'Employement': 76.4,
  'Education': 77.2,
  'Health': 65.0,
  'Crime': 61.0,
  'Housing': 80.5,
  'Living Environment': 14.6},
 'E01035686': {'Income': 48.0,
  'Employement': 26.0,
  'Education': 48.8,
  'Health': 40.2,
  'Crime': 75.6,
  'Housing': 79.7,
  'Living Environment': 85.4},
 'E01035668': {'Income': 35.8,
  'Employement': 56.1,
  'Education': 33.3,
  'Health': 87.0,
  'Crime': 97.6,
  'Housing': 35.0,
  'Living Environment': 43.9},
 'E01004257': {'Income': 94.3,
  'Employement': 82.1,
  'Education': 96.7,
  'Health': 67.5,
  'Crime': 59.3,
  'Housing': 71.5,
  'Living Environment': 71.5},
 'E01004217': {'Income': 15.4,
  'Employement': 36.6,
  'Education': 51.2,
  'Health': 19.5,
  'Crime': 86.2,
  'Housing': 69.1,
  'Living Environment': 8.9},
 'E01032783': {'Income': 23.6,
  'Employement': 31.7,
  'Education': 40.7,
  'Health': 30.1,
  'Crime': 37.4,
  'Housing': 43.1,
  'Living Environment': 9.8},
 'E01032769': {'Income': 13.0,
  'Employement': 12.2,
  'Education': 14.6,
  'Health': 40.2,
  'Crime': 93.5,
  'Housing': 22.8,
  'Living Environment': 47.2},
 'E01004313': {'Income': 68.3,
  'Employement': 56.9,
  'Education': 64.2,
  'Health': 48.0,
  'Crime': 70.7,
  'Housing': 52.8,
  'Living Environment': 80.5},
 'E01004212': {'Income': 48.0,
  'Employement': 24.8,
  'Education': 34.1,
  'Health': 24.0,
  'Crime': 95.9,
  'Housing': 43.9,
  'Living Environment': 56.9},
 'E01035705': {'Income': 62.6,
  'Employement': 70.3,
  'Education': 61.8,
  'Health': 49.6,
  'Crime': 22.8,
  'Housing': 88.6,
  'Living Environment': 10.6},
 'E01004321': {'Income': 56.1,
  'Employement': 58.5,
  'Education': 44.7,
  'Health': 20.3,
  'Crime': 36.6,
  'Housing': 100.0,
  'Living Environment': 91.1},
 'E01004301': {'Income': 86.6,
  'Employement': 73.2,
  'Education': 76.4,
  'Health': 61.8,
  'Crime': 39.4,
  'Housing': 98.4,
  'Living Environment': 92.7},
 'E01004232': {'Income': 8.9,
  'Employement': 17.5,
  'Education': 6.5,
  'Health': 3.3,
  'Crime': 88.6,
  'Housing': 11.4,
  'Living Environment': 96.7},
 'E01004251': {'Income': 64.2,
  'Employement': 53.3,
  'Education': 54.5,
  'Health': 43.1,
  'Crime': 83.7,
  'Housing': 69.9,
  'Living Environment': 31.7},
 'E01004201': {'Income': 30.9,
  'Employement': 33.7,
  'Education': 22.8,
  'Health': 22.8,
  'Crime': 22.0,
  'Housing': 46.3,
  'Living Environment': 46.3},
 'E01004308': {'Income': 49.6,
  'Employement': 62.2,
  'Education': 49.6,
  'Health': 78.5,
  'Crime': 51.2,
  'Housing': 76.4,
  'Living Environment': 52.8},
 'E01004259': {'Income': 29.7,
  'Employement': 32.5,
  'Education': 11.4,
  'Health': 33.3,
  'Crime': 54.5,
  'Housing': 50.4,
  'Living Environment': 95.1},
 'E01004293': {'Income': 3.3,
  'Employement': 6.5,
  'Education': 0.8,
  'Health': 0.8,
  'Crime': 6.5,
  'Housing': 0.8,
  'Living Environment': 40.7},
 'E01004206': {'Income': 92.7,
  'Employement': 98.4,
  'Education': 98.4,
  'Health': 91.1,
  'Crime': 82.1,
  'Housing': 66.7,
  'Living Environment': 88.6},
 'E01004245': {'Income': 52.8,
  'Employement': 40.2,
  'Education': 52.0,
  'Health': 44.7,
  'Crime': 28.5,
  'Housing': 33.3,
  'Living Environment': 8.1},
 'E01035696': {'Income': 9.8,
  'Employement': 3.7,
  'Education': 7.3,
  'Health': 13.8,
  'Crime': 9.8,
  'Housing': 3.3,
  'Living Environment': 60.2},
 'E01004296': {'Income': 40.7,
  'Employement': 44.7,
  'Education': 28.5,
  'Health': 28.5,
  'Crime': 78.9,
  'Housing': 4.1,
  'Living Environment': 17.9},
 'E01004316': {'Income': 41.5,
  'Employement': 52.0,
  'Education': 17.9,
  'Health': 74.8,
  'Crime': 64.2,
  'Housing': 99.2,
  'Living Environment': 100.0},
 'E01035667': {'Income': 69.1,
  'Employement': 70.3,
  'Education': 69.9,
  'Health': 22.0,
  'Crime': 35.0,
  'Housing': 45.5,
  'Living Environment': 27.6},
 'E01004275': {'Income': 32.5,
  'Employement': 21.1,
  'Education': 52.8,
  'Health': 18.7,
  'Crime': 7.3,
  'Housing': 37.4,
  'Living Environment': 21.1},
 'E01004302': {'Income': 81.3,
  'Employement': 73.2,
  'Education': 83.7,
  'Health': 86.2,
  'Crime': 73.6,
  'Housing': 95.1,
  'Living Environment': 67.5},
 'E01004200': {'Income': 12.2,
  'Employement': 14.2,
  'Education': 5.7,
  'Health': 57.7,
  'Crime': 29.3,
  'Housing': 28.5,
  'Living Environment': 90.2},
 'E01004309': {'Income': 83.7,
  'Employement': 85.4,
  'Education': 50.4,
  'Health': 97.6,
  'Crime': 96.7,
  'Housing': 56.9,
  'Living Environment': 68.3},
 'E01004226': {'Income': 52.0,
  'Employement': 53.3,
  'Education': 66.7,
  'Health': 64.2,
  'Crime': 74.8,
  'Housing': 9.8,
  'Living Environment': 22.8},
 'E01004222': {'Income': 58.5,
  'Employement': 89.4,
  'Education': 89.4,
  'Health': 63.4,
  'Crime': 65.9,
  'Housing': 8.9,
  'Living Environment': 23.6},
 'E01035676': {'Income': 74.0,
  'Employement': 82.9,
  'Education': 80.5,
  'Health': 46.3,
  'Crime': 35.8,
  'Housing': 82.1,
  'Living Environment': 48.8},
 'E01004199': {'Income': 77.2,
  'Employement': 86.2,
  'Education': 90.2,
  'Health': 80.5,
  'Crime': 77.6,
  'Housing': 73.2,
  'Living Environment': 55.3},
 'E01004304': {'Income': 82.1,
  'Employement': 84.1,
  'Education': 94.3,
  'Health': 29.3,
  'Crime': 43.9,
  'Housing': 97.6,
  'Living Environment': 72.4},
 'E01004221': {'Income': 33.3,
  'Employement': 29.3,
  'Education': 42.3,
  'Health': 60.2,
  'Crime': 30.1,
  'Housing': 90.2,
  'Living Environment': 29.3},
 'E01035681': {'Income': 79.7,
  'Employement': 93.5,
  'Education': 82.9,
  'Health': 69.9,
  'Crime': 26.8,
  'Housing': 55.3,
  'Living Environment': 20.3},
 'E01035661': {'Income': 66.7,
  'Employement': 41.5,
  'Education': 81.3,
  'Health': 98.4,
  'Crime': 80.5,
  'Housing': 82.9,
  'Living Environment': 49.6},
 'E01035702': {'Income': 74.8,
  'Employement': 24.8,
  'Education': 38.2,
  'Health': 15.4,
  'Crime': 58.5,
  'Housing': 5.7,
  'Living Environment': 66.7},
 'E01004287': {'Income': 96.7,
  'Employement': 78.0,
  'Education': 74.8,
  'Health': 39.0,
  'Crime': 15.0,
  'Housing': 74.8,
  'Living Environment': 30.1},
 'E01035669': {'Income': 22.8,
  'Employement': 20.3,
  'Education': 18.7,
  'Health': 75.6,
  'Crime': 99.2,
  'Housing': 54.5,
  'Living Environment': 45.5},
 'E01004326': {'Income': 53.7,
  'Employement': 42.7,
  'Education': 43.1,
  'Health': 41.5,
  'Crime': 92.7,
  'Housing': 91.1,
  'Living Environment': 89.4},
 'E01032787': {'Income': 78.9,
  'Employement': 75.6,
  'Education': 91.9,
  'Health': 30.9,
  'Crime': 46.3,
  'Housing': 70.7,
  'Living Environment': 82.1},
 'E01004277': {'Income': 0.8,
  'Employement': 5.3,
  'Education': 2.4,
  'Health': 10.2,
  'Crime': 0.8,
  'Housing': 12.2,
  'Living Environment': 12.2},
 'E01004305': {'Income': 89.4,
  'Employement': 78.9,
  'Education': 75.6,
  'Health': 32.5,
  'Crime': 31.3,
  'Housing': 91.9,
  'Living Environment': 78.9},
 'E01032782': {'Income': 16.7,
  'Employement': 14.2,
  'Education': 24.4,
  'Health': 65.9,
  'Crime': 38.2,
  'Housing': 4.9,
  'Living Environment': 57.7},
 'E01004255': {'Income': 70.7,
  'Employement': 77.2,
  'Education': 63.4,
  'Health': 83.7,
  'Crime': 81.3,
  'Housing': 58.5,
  'Living Environment': 54.5},
 'E01035679': {'Income': 38.2,
  'Employement': 22.8,
  'Education': 35.8,
  'Health': 36.6,
  'Crime': 79.7,
  'Housing': 21.1,
  'Living Environment': 26.8},
 'E01035674': {'Income': 28.5,
  'Employement': 30.5,
  'Education': 21.1,
  'Health': 53.7,
  'Crime': 18.7,
  'Housing': 17.9,
  'Living Environment': 15.4},
 'E01004266': {'Income': 42.7,
  'Employement': 45.5,
  'Education': 25.2,
  'Health': 48.8,
  'Crime': 15.0,
  'Housing': 49.6,
  'Living Environment': 74.0},
 'E01035663': {'Income': 21.5,
  'Employement': 26.8,
  'Education': 32.5,
  'Health': 17.9,
  'Crime': 19.5,
  'Housing': 26.0,
  'Living Environment': 77.2},
 'E01032765': {'Income': 31.7,
  'Employement': 54.5,
  'Education': 68.3,
  'Health': 72.4,
  'Crime': 24.4,
  'Housing': 14.6,
  'Living Environment': 16.3},
 'E01004307': {'Income': 4.1,
  'Employement': 5.3,
  'Education': 3.3,
  'Health': 7.3,
  'Crime': 4.9,
  'Housing': 63.4,
  'Living Environment': 98.4},
 'E01032767': {'Income': 2.4,
  'Employement': 0.8,
  'Education': 13.0,
  'Health': 8.9,
  'Crime': 2.4,
  'Housing': 6.5,
  'Living Environment': 61.8},
 'E01004205': {'Income': 91.9,
  'Employement': 88.6,
  'Education': 71.5,
  'Health': 77.2,
  'Crime': 69.9,
  'Housing': 85.4,
  'Living Environment': 70.7},
 'E01004247': {'Income': 82.9,
  'Employement': 80.5,
  'Education': 88.6,
  'Health': 82.9,
  'Crime': 82.9,
  'Housing': 61.0,
  'Living Environment': 30.9},
 'E01004315': {'Income': 27.6,
  'Employement': 60.2,
  'Education': 29.3,
  'Health': 51.2,
  'Crime': 90.2,
  'Housing': 39.8,
  'Living Environment': 75.6},
 'E01004310': {'Income': 39.8,
  'Employement': 50.8,
  'Education': 27.6,
  'Health': 70.7,
  'Crime': 68.7,
  'Housing': 59.3,
  'Living Environment': 82.9},
 'E01035692': {'Income': 48.0,
  'Employement': 38.2,
  'Education': 26.8,
  'Health': 62.6,
  'Crime': 42.3,
  'Housing': 38.2,
  'Living Environment': 2.4},
 'E01035666': {'Income': 61.8,
  'Employement': 55.3,
  'Education': 61.0,
  'Health': 42.3,
  'Crime': 32.9,
  'Housing': 48.8,
  'Living Environment': 17.1},
 'E01035687': {'Income': 20.3,
  'Employement': 9.3,
  'Education': 20.3,
  'Health': 10.2,
  'Crime': 71.5,
  'Housing': 30.1,
  'Living Environment': 63.4},
 'E01004248': {'Income': 95.9,
  'Employement': 91.5,
  'Education': 93.5,
  'Health': 100.0,
  'Crime': 48.0,
  'Housing': 57.7,
  'Living Environment': 39.8},
 'E01004319': {'Income': 66.7,
  'Employement': 49.2,
  'Education': 65.0,
  'Health': 31.7,
  'Crime': 27.6,
  'Housing': 92.7,
  'Living Environment': 51.2},
 'E01032764': {'Income': 26.8,
  'Employement': 36.6,
  'Education': 26.0,
  'Health': 61.0,
  'Crime': 84.6,
  'Housing': 8.1,
  'Living Environment': 35.8},
 'E01004237': {'Income': 78.0,
  'Employement': 65.4,
  'Education': 53.7,
  'Health': 69.1,
  'Crime': 72.4,
  'Housing': 40.7,
  'Living Environment': 37.4},
 'E01004311': {'Income': 59.3,
  'Employement': 63.8,
  'Education': 39.0,
  'Health': 45.5,
  'Crime': 60.2,
  'Housing': 13.0,
  'Living Environment': 65.0},
 'E01004243': {'Income': 61.0,
  'Employement': 65.4,
  'Education': 86.2,
  'Health': 58.5,
  'Crime': 17.9,
  'Housing': 56.1,
  'Living Environment': 52.0},
 'E01004270': {'Income': 17.9,
  'Employement': 17.5,
  'Education': 15.4,
  'Health': 17.1,
  'Crime': 68.7,
  'Housing': 52.0,
  'Living Environment': 81.3},
 'E01004219': {'Income': 54.5,
  'Employement': 28.0,
  'Education': 46.3,
  'Health': 25.2,
  'Crime': 77.6,
  'Housing': 19.5,
  'Living Environment': 79.7},
 'E01035660': {'Income': 43.9,
  'Employement': 49.2,
  'Education': 30.1,
  'Health': 76.4,
  'Crime': 95.1,
  'Housing': 31.7,
  'Living Environment': 76.4},
 'E01004260': {'Income': 73.2,
  'Employement': 67.9,
  'Education': 78.0,
  'Health': 92.7,
  'Crime': 87.0,
  'Housing': 44.7,
  'Living Environment': 32.5},
 nan: {'Income': nan,
  'Employement': nan,
  'Education': nan,
  'Health': nan,
  'Crime': nan,
  'Housing': nan,
  'Living Environment': nan},
 'E01004298': {'Income': 86.6,
  'Employement': 100.0,
  'Education': 79.7,
  'Health': 95.9,
  'Crime': 66.7,
  'Housing': 87.0,
  'Living Environment': 69.1},
 'E01004292': {'Income': 1.6,
  'Employement': 1.6,
  'Education': 1.6,
  'Health': 4.9,
  'Crime': 1.6,
  'Housing': 1.6,
  'Living Environment': 4.1},
 'E01004288': {'Income': 80.5,
  'Employement': 81.3,
  'Education': 91.1,
  'Health': 59.3,
  'Crime': 52.8,
  'Housing': 94.3,
  'Living Environment': 34.1},
 'E01004264': {'Income': 93.5,
  'Employement': 84.1,
  'Education': 99.2,
  'Health': 78.5,
  'Crime': 73.6,
  'Housing': 39.0,
  'Living Environment': 62.6},
 'E01004231': {'Income': 56.9,
  'Employement': 73.2,
  'Education': 69.1,
  'Health': 93.5,
  'Crime': 91.9,
  'Housing': 27.6,
  'Living Environment': 33.3},
 'E01004229': {'Income': 35.0,
  'Employement': 50.8,
  'Education': 45.5,
  'Health': 26.8,
  'Crime': 31.3,
  'Housing': 10.6,
  'Living Environment': 50.4},
 'E01004289': {'Income': 55.3,
  'Employement': 66.7,
  'Education': 67.5,
  'Health': 82.1,
  'Crime': 50.4,
  'Housing': 87.8,
  'Living Environment': 73.2},
 'E01035682': {'Income': 72.0,
  'Employement': 63.8,
  'Education': 55.3,
  'Health': 99.2,
  'Crime': 62.6,
  'Housing': 81.3,
  'Living Environment': 42.3},
 'E01032770': {'Income': 6.9,
  'Employement': 3.7,
  'Education': 17.1,
  'Health': 26.0,
  'Crime': 8.1,
  'Housing': 18.7,
  'Living Environment': 0.8},
 'E01032780': {'Income': 16.7,
  'Employement': 9.3,
  'Education': 9.8,
  'Health': 8.1,
  'Crime': 5.7,
  'Housing': 26.8,
  'Living Environment': 87.8},
 'E01035680': {'Income': 25.2,
  'Employement': 18.7,
  'Education': 10.6,
  'Health': 73.2,
  'Crime': 12.2,
  'Housing': 29.3,
  'Living Environment': 5.7},
 'E01035685': {'Income': 97.6,
  'Employement': 96.7,
  'Education': 100.0,
  'Health': 55.3,
  'Crime': 56.1,
  'Housing': 77.2,
  'Living Environment': 13.0},
 'E01035697': {'Income': 14.6,
  'Employement': 22.0,
  'Education': 13.8,
  'Health': 47.2,
  'Crime': 3.3,
  'Housing': 32.5,
  'Living Environment': 64.2},
 'E01004208': {'Income': 19.5,
  'Employement': 19.5,
  'Education': 8.1,
  'Health': 37.4,
  'Crime': 100.0,
  'Housing': 62.6,
  'Living Environment': 91.9},
 'E01035706': {'Income': 8.1,
  'Employement': 7.3,
  'Education': 12.2,
  'Health': 4.1,
  'Crime': 23.6,
  'Housing': 15.4,
  'Living Environment': 25.2},
 'E01035693': {'Income': 21.5,
  'Employement': 23.6,
  'Education': 23.6,
  'Health': 71.5,
  'Crime': 49.2,
  'Housing': 23.6,
  'Living Environment': 7.3},
 'E01004202': {'Income': 18.7,
  'Employement': 28.0,
  'Education': 30.9,
  'Health': 11.4,
  'Crime': 55.3,
  'Housing': 42.3,
  'Living Environment': 65.9},
 'E01004230': {'Income': 34.1,
  'Employement': 43.9,
  'Education': 37.4,
  'Health': 21.1,
  'Crime': 34.1,
  'Housing': 16.3,
  'Living Environment': 84.6},
 'E01004300': {'Income': 88.6,
  'Employement': 91.5,
  'Education': 78.9,
  'Health': 79.7,
  'Crime': 16.3,
  'Housing': 95.9,
  'Living Environment': 83.7},
 'E01032774': {'Income': 29.7,
  'Employement': 39.0,
  'Education': 47.2,
  'Health': 52.8,
  'Crime': 10.6,
  'Housing': 41.5,
  'Living Environment': 1.6},
 'E01035678': {'Income': 46.3,
  'Employement': 40.2,
  'Education': 39.8,
  'Health': 16.3,
  'Crime': 40.7,
  'Housing': 17.1,
  'Living Environment': 19.5},
 'E01035677': {'Income': 66.7,
  'Employement': 58.5,
  'Education': 43.9,
  'Health': 88.6,
  'Crime': 41.5,
  'Housing': 25.2,
  'Living Environment': 18.7},
 'E01004271': {'Income': 57.7,
  'Employement': 33.7,
  'Education': 35.0,
  'Health': 38.2,
  'Crime': 25.2,
  'Housing': 53.7,
  'Living Environment': 22.0},
 'E01004214': {'Income': 100.0,
  'Employement': 99.2,
  'Education': 95.1,
  'Health': 85.0,
  'Crime': 21.1,
  'Housing': 93.5,
  'Living Environment': 6.5},
 'E01004209': {'Income': 90.2,
  'Employement': 87.8,
  'Education': 84.6,
  'Health': 85.0,
  'Crime': 63.4,
  'Housing': 74.0,
  'Living Environment': 95.9},
 'E01004218': {'Income': 10.6,
  'Employement': 15.9,
  'Education': 8.9,
  'Health': 1.6,
  'Crime': 4.1,
  'Housing': 68.3,
  'Living Environment': 4.9},
 'E01035694': {'Income': 84.6,
  'Employement': 94.3,
  'Education': 72.8,
  'Health': 89.8,
  'Crime': 76.4,
  'Housing': 60.2,
  'Living Environment': 44.7},
 'E01004324': {'Income': 76.4,
  'Employement': 79.7,
  'Education': 92.7,
  'Health': 68.3,
  'Crime': 39.4,
  'Housing': 96.7,
  'Living Environment': 24.4}}

In [ ]:
#Now we turn it into a function to use in the spider diagram
def get_imd_rankings_per_lsoa(df):
    imd_column_names = list(imd_categories_breakdown.keys())
    lsoa_imd_scores = df.drop_duplicates(subset="lsoaCode")[["lsoaCode"] + imd_column_names].copy()
    for i, j in imd_categories_breakdown.items():
        lsoa_imd_scores[f"{i}_percentage"] = lsoa_imd_scores[i].rank(pct=True) * 100

    lsoa_imd_dict = {}
    for _, j in lsoa_imd_scores.iterrows():
        lsoa_code = j["lsoaCode"]
        lsoa_imd_dict[lsoa_code] = {
            label: round(j[f"{i}_percentage"], 1) for i, label in imd_categories_breakdown.items()}
    return lsoa_imd_dict

In [ ]:
def build_spider_chart(lsoa_code):
    lsoa_ranks = get_imd_rankings_per_lsoa(df)
    lsoa_ranks = lsoa_ranks.get(lsoa_code)
    
    if not lsoa_ranks:
        return None

    lsoas = list(lsoa_ranks.keys())
    imd_scores = list(lsoa_ranks.values())
    lsoas.append(lsoas[0])
    imd_scores.append(imd_scores[0])

    fig = go.Figure()

    fig.add_trace(go.Scatterpolar(
    r = imd_scores,
    theta =lsoas,
    fill ="toself",
    fillcolor ="rgba(248, 113, 113, 0.15)",
    line =dict(color="#c11d1d", width=2),
    name =f"{lsoa_code}",
    hovertemplate="%{theta}: %{r:.0f}th percentile<extra></extra>",))


    return fig

In [77]:
build_spider_chart('E01004306')