In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../charity_watch_streamlit/data/charities_with_deprivation.csv")

In [3]:
imd_categories_breakdown = {
    "incomeScore":"Income",
    "employmentRate":'Employement',
    "educationSkillsTrainingScore": "Education",
    "healthDeprivation":"Health",
    "crimeDeprivation" :"Crime",
    "housingBarriersDeprivation":"Housing",
    "livingEnvScore":"Living Environment",
}

In [4]:
imd_column_names = list(imd_categories_breakdown.keys())
imd_column_names

['incomeScore',
 'employmentRate',
 'educationSkillsTrainingScore',
 'healthDeprivation',
 'crimeDeprivation',
 'housingBarriersDeprivation',
 'livingEnvScore']

In [ ]:
lsoa_imd_scores = df.drop_duplicates(subset="lsoaCode")[["lsoaCode"] + imd_column_names].copy()

In [6]:
lsoa_imd_scores

,lsoaCode,incomeScore,employmentRate,educationSkillsTrainingScore,healthDeprivation,crimeDeprivation,housingBarriersDeprivation,livingEnvScore
0,E01004306,0.387,0.190,15.221,0.546,0.730,38.717,48.653
1,E01004204,0.472,0.191,18.864,0.728,0.473,32.576,44.911
2,E01035690,0.237,0.073,13.312,-0.030,0.153,26.087,24.595
3,E01004295,0.602,0.153,21.833,-0.004,0.188,42.923,35.935
4,E01004286,0.432,0.223,19.673,0.458,0.953,37.938,39.925
...,...,...,...,...,...,...,...,...
277,E01004214,0.730,0.257,31.042,0.853,0.230,46.035,21.057
287,E01004209,0.599,0.225,25.547,0.853,0.714,38.226,49.823
290,E01004218,0.232,0.099,6.022,-0.716,-0.430,37.046,16.663
291,E01035694,0.573,0.246,22.486,0.950,0.794,35.705,33.370
293,E01004324,0.537,0.207,27.841,0.680,0.440,46.943,27.103

In [ ]:
for i, j in imd_categories_breakdown.items():
        lsoa_imd_scores[f"{i}_percentage"] = lsoa_imd_scores[i].rank(pct=True) * 100

In [9]:
lsoa_imd_scores

,lsoaCode,incomeScore,employmentRate,educationSkillsTrainingScore,healthDeprivation,crimeDeprivation,housingBarriersDeprivation,livingEnvScore,incomeScore_pct,employmentRate_pct,educationSkillsTrainingScore_pct,healthDeprivation_pct,crimeDeprivation_pct,housingBarriersDeprivation_pct,livingEnvScore_pct
0,E01004306,0.387,0.190,15.221,0.546,0.730,38.717,48.653,39.024390,67.886179,47.967480,56.097561,65.040650,75.609756,94.308943
1,E01004204,0.472,0.191,18.864,0.728,0.473,32.576,44.911,60.162602,70.325203,62.601626,73.983740,43.089431,47.154472,86.178862
2,E01035690,0.237,0.073,13.312,-0.030,0.153,26.087,24.595,11.382114,10.569106,36.585366,13.008130,17.073171,20.325203,13.821138
3,E01004295,0.602,0.153,21.833,-0.004,0.188,42.923,35.935,91.056911,46.341463,70.731707,14.634146,20.325203,89.430894,60.975610
4,E01004286,0.432,0.223,19.673,0.458,0.953,37.938,39.925,51.219512,86.991870,65.853659,50.406504,89.430894,72.357724,74.796748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,E01004214,0.730,0.257,31.042,0.853,0.230,46.035,21.057,100.000000,99.186992,95.121951,84.959350,21.138211,93.495935,6.504065
287,E01004209,0.599,0.225,25.547,0.853,0.714,38.226,49.823,90.243902,87.804878,84.552846,84.959350,63.414634,73.983740,95.934959
290,E01004218,0.232,0.099,6.022,-0.716,-0.430,37.046,16.663,10.569106,15.853659,8.943089,1.626016,4.065041,68.292683,4.878049
291,E01035694,0.573,0.246,22.486,0.950,0.794,35.705,33.370,84.552846,94.308943,72.764228,89.837398,76.422764,60.162602,44.715447
293,E01004324,0.537,0.207,27.841,0.680,0.440,46.943,27.103,76.422764,79.674797,92.682927,68.292683,39.430894,96.747967,24.390244

In [ ]:
lsoa_imd_dict = {}

In [ ]:
#now we turn this dataframe into a dictionary of dictionaries, one lsoa key and its imd scores as values
for _, j in lsoa_imd_scores.iterrows():
    lsoa_code = j["lsoaCode"]
    lsoa_imd_dict[lsoa_code] = {
        label: round(j[f"{i}_percentage"], 1) for i, label in imd_categories_breakdown.items()}

In [ ]:
lsoa_imd_dict

In [ ]:
#Now we turn it into a function to use in the spider diagram
def get_imd_rankings__per_lsoa(df):
    imd_column_names = list(imd_categories_breakdown.keys())
    lsoa_imd_scores = df.drop_duplicates(subset="lsoaCode")[["lsoaCode"] + imd_column_names].copy()
    for i, j in imd_categories_breakdown.items():
        lsoa_imd_scores[f"{i}_percentage"] = lsoa_imd_scores[i].rank(pct=True) * 100

    lsoa_imd_dict = {}
    for _, j in lsoa_imd_scores.iterrows():
        lsoa_code = j["lsoaCode"]
        lsoa_imd_dict[lsoa_code] = {
            label: round(j[f"{i}_percentage"], 1) for i, label in imd_categories_breakdown.items()}
    return lsoa_imd_dict